package com.newyorktaxi.utility

object NewYorkTaxiConstants {
    val tpep_pickup_datetime_colName = "tpep_pickup_datetime"
    val dateFormat = "yyyy-MM-dd"
    val taxi_id_colName = "taxi_id"
    val h3_index_colName = "h3_index"
    val h3_index_hex_colName = "h3_index_hex"
    val zone_colName = "zone"
    val borough_colName = "borough"
    val pickup_zone_colName = "pickup_zone"
    val pickup_borough_colName = "pickup_borough"
    val number_of_pickups_alias = "number_of_pickups"
    val dropoff_zone_colName = "dropoff_zone"
    val dropoff_borough_colName = "dropoff_borough"
    val number_of_dropoffs_alias = "number_of_dropoffs"
    val number_of_dropoffs_colName = "number_of_dropoffs"
    val trip_distance_round_colName = "trip_distance_round"
    val average_total_fare_alias = "average_total_fare"
    val number_of_trips_alias = "number_of_trips"
    val trip_distance_colName = "trip_distance"
    val average_trip_distance_alias = "average_trip_distance"
    val total_amount_colName = "total_amount"
    val rank_colName = "rank"
    val pickup_date_colName = "pickup_date"
    val pickup_date_hour_colName = "pickup_date_hour"
    val no_of_trips_per_hour_alias = "no_of_trips_per_hour"
    val no_of_trips_per_hour_colName = "no_of_trips_per_hour"
    val average_trips_alias = "average_trips"
    val hour_of_day_colName = "hour_of_day"
    val analytics_type_one = "insight1"
    val analytics_task_ten = "task10"
    val analytics_type_two = "insight2"
    val analytics_type_three = "insight3"
    val analytics_type_four = "insight4"
    val analytics_type_five = "insight5"
    val analytics_type_six = "insight6"
    val analytics_type_seven = "insight7"
}
